### PR TITLE
Align depts -> jobs -> skills on change

### LINKED ISSUE #79: unaligned jobs and skills maintained despite deselection of parent
When editing a credit and unselecting a department or job/position, any corresponding selected jobs or skills will no longer be visible but maintain their selected status, as seen upon save in the gif reproduction below. 

Rise-bug-credits

### PR DESCRIPTION
**Pull request by ari-denary**
Deselection of a department also unselects any tied jobs and skills that are no longer tied to a selected department. Same applies to deselection of a job with tied skills.
Fixes #79 
rise-bug-credits-fix

While working on this, it was also discovered that the data type held within selected skills, jobs, and departments changes from an array of numbers to an array of strings upon user input. 

Problem shown here:
rise-data-type-diff

Fixed result maintains number array data type:
rise-data-diff-fix

### CODE REVIEW

**Comment by gaswirth** [comment]
I can't accept any PRs to the `main` branch (check the README). When you started your work, did you clone `dev` or `main`?

**Comment by gaswirth** [comment]
(Didn't mean to close yet)

**Comment by ari-denary** [comment]
Hmm... I thought I cloned & branched from dev, but git has a more accurate memory than my brain, so it must've been main. I'll work on transferring this to a branch off of dev and resend.

**Comment by gaswirth** [comment]
Sending a longer reply shortly, but I'm reviewing your code and it does look like you cloned `dev`. Check to make sure, but I think that's all good!

**Review by gaswirth — COMMENTED** [review]
I gotta say, this is a really great update! Changing `useRelatedSkills` to a lazy query has been on my list for months, and has completely fallen through the cracks. It's a great fix!

Tonight or tomorrow I'll look in-depth, but this is awesome!

**Comment by gaswirth** [comment]
One note, though - DeepScan is failing. Can you please check the Details above (they're public) and hit those items so all 5 tests pass? Thanks!

**Comment by ari-denary** [comment]
Thanks! And yes absolutely!

**Comment by ari-denary** [comment]
Thanks so much for your patience Nick! I learned a lot from this - and realized what I did that was having this merge to main originally. I believe this is fixed now. Would you prefer I delete or close the duplicate pull request & branch I opened?

**Comment by gaswirth** [comment]
Great! Please delete the dupe, and confirm that you're ready for me to review here. Thanks!

**Comment by ari-denary** [comment]
Ready for your review :)

**Review by gaswirth — COMMENTED** [review]
Looks good! I'm making a few formatting and stylistic tweaks, but all super minor. Merging into dev shortly! 🚀

**Review by gaswirth — APPROVED** [review]

**Comment by gaswirth** [comment]
Thanks for your work on this, @ari-denary!

**Comment by ari-denary** [comment]
Amazing! Thank you Nick!

**Pull request merged**
